[[config]]
languages = ["python"]
line_comment = "#"
top_level_keywords = ["def", "from", "class", "import"]

[[config]]
languages = ["rust"]
line_comment = "//"
top_level_keywords = [
    "fn",
    "trait",
    "impl",
    "enum",
    "pub",
    "extern",
    "static",
    "trait",
    "unsafe",
    "use",
]

[[config]]
languages = ["javascript", "typescript", "javascriptreact", "typescriptreact"]
line_comment = "//"
top_level_keywords = [
    "abstract",
    "async",
    "class",
    "const",
    "export",
    "function",
    "interface",
    "module",
    "package",
    "type",
    "var",
    "enum",
    "let",
]

[[config]]
languages = ["go"]
line_comment = "//"
top_level_keywords = [
    "func",
    "interface",
    "struct",
    "package",
    "type",
    "import",
    "var",
    "const",
]

[[config]]
languages = ["ruby"]
line_comment = "#"
# from https://docs.ruby-lang.org/en/3.2/keywords_rdoc.html
top_level_keywords = [
    "__ENCODING__",
    "__LINE__",
    "__FILE__",
    "BEGIN",
    "END",
    "alias",
    "and",
    "begin",
    "break",
    "case",
    "class",
    "def",
    "defined?",
    "do",
    "else",
    "elsif",
    "end",
    "ensure",
    "false",
    "for",
    "if",
    "in",
    "module",
    "next",
    "nil",
    "not",
    "or",
    "redo",
    "rescue",
    "retry",
    "return",
    "self",
    "super",
    "then",
    "true",
    "undef",
    "unless",
    "until",
    "when",
    "while",
    "yield",
]
